### ISSUE TITLE
Issue with tensorflow

### ISSUE THREAD

**Issue by sri3705** [farizrahman4u/seq2seq#100]
Hi,
Here is a very small snippet of code that I tried to run:
>>> model = SimpleSeq2Seq(output_dim=output_dim, output_length=output_length, input_shape=
(input_length, input_dim))

I get the folllowing error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "build/bdist.linux-x86_64/egg/seq2seq/models.py", line 76, in SimpleSeq2Seq
  File "/mnt/ssd6/srikanth/anaconda2/lib/python2.7/site-packages/keras/models.py", line 276, in add
    layer.create_input_layer(batch_input_shape, input_dtype)
  File "/mnt/ssd6/srikanth/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 371, in create_input_layer
    self(x)
  File "/mnt/ssd6/srikanth/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 515, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/mnt/ssd6/srikanth/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 573, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/mnt/ssd6/srikanth/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 150, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "build/bdist.linux-x86_64/egg/recurrentshop/engine.py", line 296, in call
  File "build/bdist.linux-x86_64/egg/recurrentshop/engine.py", line 51, in <lambda>
  File "/mnt/ssd6/srikanth/anaconda2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1135, in rnn
    state_size = int(states[0].get_shape()[-1])
TypeError: __int__ returned non-int (type NoneType)

**Comment by farizrahman4u** [comment]
@meain Please look into this.

**Comment by StephanHeijl** [comment]
I have encountered the same problem, it looks like it is related to requesting the shape of a state before the model is initialized in TensorFlow. Unfortunately I currently lack the TF experience to resolve this.

**Comment by meain** [comment]
@sri3705 Could you try with unroll set to True.

**Comment by farizrahman4u** [comment]
Use unroll=True. This has to be fixed on keras side.

**Comment by sri3705** [comment]
Works fine. Thanks!
