### ISSUE TITLE
Tensorflow backend, TypeError: can only concatenate tuple (not "list") to tuple

### ISSUE THREAD

**Issue by hossein-h** [farizrahman4u/seq2seq#107]
I installed seq2seq successfully and it works with theano backend. But, when I switch to TensorFlow and run the following:

model = SimpleSeq2Seq(output_dim=output_dim, output_length=output_length, input_shape=(input_length, input_dim))

I get this error:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda2/lib/python2.7/site-packages/seq2seq/models.py", line 76, in SimpleSeq2Seq
    model.add(encoder)
  File "/opt/anaconda2/lib/python2.7/site-packages/keras/models.py", line 276, in add
    layer.create_input_layer(batch_input_shape, input_dtype)
  File "/opt/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 370, in create_input_layer
    self(x)
  File "/opt/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 514, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/opt/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 572, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/opt/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 149, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/opt/anaconda2/lib/python2.7/site-packages/recurrentshop-0.0.1-py2.7.egg/recurrentshop/engine.py", line 296, in call
  File "/opt/anaconda2/lib/python2.7/site-packages/recurrentshop-0.0.1-py2.7.egg/recurrentshop/engine.py", line 51, in <lambda>
TypeError: can only concatenate tuple (not "list") to tuple

Thanks for the help.

**Comment by farizrahman4u** [comment]
fixed.
