### ISSUE TITLE
IndexError: index 3 is out of bounds for axis 0 with size 3

### ISSUE THREAD

**Issue by nicolas-ivanov** [farizrahman4u/seq2seq#11]
Dear humans,
either I'm missimg something or there is a bug in Fariz's seq2seq implementation. What's your bet?

Code:
```python
import numpy as np
from keras.models import Sequential
from seq2seq.seq2seq import Seq2seq


vocab_size = 10 #number of words
maxlen = 3 #length of input sequence and output sequence
embedding_dim = 5 #word embedding size
hidden_dim = 50 #memory size of seq2seq
batch_size = 7

seq2seq = Seq2seq(input_length=maxlen,
                  input_dim=embedding_dim,
                  hidden_dim=hidden_dim,
                  output_dim=vocab_size,
                  output_length=maxlen,
                  batch_size=batch_size,
                  depth=1)

print 'Build model ...'
model = Sequential()
model.add(seq2seq)
model.compile(loss='mse', optimizer='adam')

print 'Generate dummy data ...'
train_examples_num = batch_size
X = np.zeros((train_examples_num, maxlen, embedding_dim))
Y = np.zeros((train_examples_num, maxlen, vocab_size))

for train_example_idx in xrange(train_examples_num):
    for word_idx in xrange(maxlen):
        w2v_vector = np.random.rand(1, embedding_dim)[0]
        X[train_example_idx][word_idx] = w2v_vector

        bool_vector = np.zeros(vocab_size)
        bool_vector[np.random.choice(vocab_size)] = 1
        Y[train_example_idx][word_idx] = bool_vector

print X.shape, X
print Y.shape, Y

print 'Fit data ...'
model.fit(X, Y)
```

Log:
```
Build model ...
/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan_perform_ext.py:133: RuntimeWarning: numpy.ndarray size changed, may indicate binary incompatibility
  from scan_perform.scan_perform import *
Generate dummy data ...
(7, 3, 5) [[[ 0.88256245  0.77128004  0.11195964  0.0918089   0.57508599]
  [ 0.23917097  0.69324662  0.5007371   0.08220433  0.25601655]
  [ 0.31997691  0.96215576  0.37516188  0.4564258   0.44645146]]

 [[ 0.1164474   0.68527686  0.48801347  0.06237132  0.64461641]
  [ 0.21418609  0.56414103  0.69280567  0.09577648  0.46501309]
  [ 0.59522824  0.82593701  0.8952664   0.61032139  0.60784708]]

 [[ 0.50277342  0.18204284  0.6920746   0.23992536  0.5031889 ]
  [ 0.24719549  0.39098328  0.84927183  0.93091596  0.93981078]
  [ 0.76817661  0.68241358  0.97509582  0.78777374  0.41076285]]

 [[ 0.83762506  0.76151013  0.06292322  0.71097064  0.77048028]
  [ 0.78948919  0.77401108  0.39082489  0.66905667  0.54795132]
  [ 0.74940861  0.26011439  0.23257989  0.87033028  0.88954607]]

 [[ 0.98032484  0.29076576  0.76085615  0.53828208  0.92028479]
  [ 0.81111357  0.52959467  0.41101679  0.39434533  0.47918241]
  [ 0.18741232  0.68735943  0.27534715  0.18796185  0.89010293]]

 [[ 0.00484476  0.38136868  0.55200039  0.36352682  0.65304447]
  [ 0.19502873  0.86442676  0.82170956  0.90937185  0.93152998]
  [ 0.71814645  0.47181875  0.99475651  0.24588243  0.13357496]]

 [[ 0.92716079  0.83195725  0.50047687  0.86742848  0.27778597]
  [ 0.90902709  0.60421839  0.17206286  0.53972434  0.9863197 ]
  [ 0.63227496  0.14045515  0.88635036  0.72415621  0.88298206]]]
(7, 3, 10) [[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
  [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
  [ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  1.  0.]]

 [[ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
  [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]]

 [[ 0.  0.  0.  0.  0.  0.  1.  0.  0.  0.]
  [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]]

 [[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  1.]
  [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]]]
Fit data ...
Epoch 1/100
Traceback (most recent call last):
  File "/home/nicolas/Code/seq2seq/bin/try.py", line 43, in <module>
    model.fit(X, Y)
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 495, in fit
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 216, in _fit
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 606, in __call__
    storage_map=self.fn.storage_map)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 595, in __call__
    outputs = self.fn()
  File "/usr/local/lib/python2.7/dist-packages/theano/gof/op.py", line 768, in rval
    r = p(n, [x[0] for x in i], o)
  File "/usr/local/lib/python2.7/dist-packages/theano/tensor/subtensor.py", line 2088, in perform
    out[0] = inputs[0].__getitem__(inputs[1:])
IndexError: index 3 is out of bounds for axis 0 with size 3
Apply node that caused the error: AdvancedSubtensor(Subtensor{int64::}.0, Subtensor{int64}.0, Subtensor{int64}.0)
Inputs types: [TensorType(float64, 3D), TensorType(int64, vector), TensorType(int64, vector)]
Inputs shapes: [(3, 7, 10), (21,), (21,)]
Inputs strides: [(560, 80, 8), (8,), (8,)]
Inputs values: ['not shown', 'not shown', 'not shown']

Backtrace when the node is created:
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 75, in weighted
    filtered_y_pred = y_pred[weights.nonzero()[:-1]]
```

Repo with the source for your convenience: https://github.com/nicolas-ivanov/seq2seq

**Comment by farizrahman4u** [comment]
Can you run it after removing this piece:
```python
for train_example_idx in xrange(train_examples_num):
    for word_idx in xrange(maxlen):
        w2v_vector = np.random.rand(1, embedding_dim)[0]
        X[train_example_idx][word_idx] = w2v_vector

        bool_vector = np.zeros(vocab_size)
        bool_vector[np.random.choice(vocab_size)] = 1
        Y[train_example_idx][word_idx] = bool_vector
```

**Comment by nicolas-ivanov** [comment]
Fariz, after removing I get absolutely the same error message...

**Comment by farizrahman4u** [comment]
It works for me when using sgd optimizer. Can you try that?

**Comment by nicolas-ivanov** [comment]
Tried sgd and got the same error

**Comment by farizrahman4u** [comment]
@nicolas-ivanov Are you fitting with the right batch size? Your training batch size should be same as the batch size argument of seq2seq.

**Comment by farizrahman4u** [comment]
Try `model.fit(X,Y, batch_size=7)`

**Comment by nicolas-ivanov** [comment]
The same :(

**Comment by farizrahman4u** [comment]
Fixed. Reinstall and run again.Thanks for reporting this!

**Comment by nicolas-ivanov** [comment]
Thank you, Fariz! `model.fit()` works now.
Can't say the same about `model.predict()`, but this issue will be reported in a separate thread :)
