### ISSUE TITLE
Error on saving model

### ISSUE THREAD

**Issue by ishalyminov** [farizrahman4u/seq2seq#125]
```
bwlf02:~/data/seq2seq$ python
Python 2.7.12 (default, Jun 28 2016, 17:49:40) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import seq2seq
Using Theano backend.
>>> from seq2seq.models import AttentionSeq2Seq
>>> 
>>> model = AttentionSeq2Seq(input_dim=5, input_length=7, hidden_dim=10, output_length=8, output_dim=20, depth=4)
>>> model.compile(loss='mse', optimizer='rmsprop')
>>> model.save('1.h5', overwrite=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/is33/Envs/alexa_seq2seq/lib/python2.7/site-packages/keras/engine/topology.py", line 2423, in save
    save_model(self, filepath, overwrite)
  File "/home/is33/Envs/alexa_seq2seq/lib/python2.7/site-packages/keras/models.py", line 52, in save_model
    'config': model.get_config()
  File "/home/is33/Envs/alexa_seq2seq/lib/python2.7/site-packages/keras/engine/topology.py", line 2285, in get_config
    layer_config = layer.get_config()
  File "/home/is33/data/recurrentshop/recurrentshop/engine.py", line 497, in get_config
    config['model'] = self.model.get_config()
  File "/home/is33/Envs/alexa_seq2seq/lib/python2.7/site-packages/keras/models.py", line 967, in get_config
    'config': layer.get_config()})
  File "seq2seq/cells.py", line 110, in get_config
    base_config = super(LSTMDecoderCell, self).get_config()
TypeError: super(type, obj): obj must be an instance or subtype of type
```

**Comment by ishalyminov** [comment]
`base_config = super(AttentionDecoderCell, self).get_config()` - this fixes it

**Comment by ishalyminov** [comment]
With that fixed, the next problem:
```
import seq2seq
from seq2seq.models import AttentionSeq2Seq

model = AttentionSeq2Seq(input_dim=5, input_length=7, hidden_dim=10, output_length=8, output_dim=20, depth=4)
model.compile(loss='mse', optimizer='rmsprop')
conf = model.get_config()
model.save('1')
```

```
File "h5py/h5o.pyx", line 202, in h5py.h5o.link (/tmp/pip-4rPeHA-build/h5py/h5o.c:3731)
RuntimeError: Unable to create link (Name already exists)
```

There are suggestions that non-unique layer names cause this problem ([https://groups.google.com/forum/#!topic/keras-users/my13TUe2dlU](https://groups.google.com/forum/#!topic/keras-users/my13TUe2dlU)), but I haven't seen any duplicate names in this model.

**Comment by ishalyminov** [comment]
The problem only rises when AttentionSeq2Seq is built with `bidirectional=True`

**Comment by phdowling** [comment]
Any progress on this? Having the same problem.

**Comment by ishalyminov** [comment]
no, just gave up on bidirectional for now..

**Comment by phdowling** [comment]
@ishalyminov I'm using this workaround for now (via https://github.com/farizrahman4u/seq2seq/issues/129):

```python
import new

def save_weights(_self, fname, overwrite=True):
    if not overwrite and os.path.isfile(fname):
        proceed = ask_to_proceed_with_overwrite(fname)
        if not proceed:
            return
    outf = h5py.File(fname, 'w')
    weight = _self.get_weights()
    for i in range(len(weight)):
        outf.create_dataset('weight' + str(i), data=weight[i])
    outf.close()

def load_weights(_self, fname):
    infile = h5py.File(fname, 'r')
    weight = []
    for i in range(len(infile.keys())):
        weight.append(infile['weight' + str(i)][:])
    _self.set_weights(weight)

model.save_weights = new.instancemethod(save_weights, model, None)
model.load_weights = new.instancemethod(load_weights, model, None)
```

This seems to work, but I haven't fully tested yet.

**Comment by farizrahman4u** [comment]
Does anyone have non-hackish solution for this? Writing your own Bidirectional wrapper is acceptable..
Am quite busy with some other stuff.

**Comment by xiangyanchao** [comment]
the bug is here fixed:
at : recurrentshop.engine.RNNCell.from_config
![9e755e4d-bbaa-4181-a302-276323453091](https://cloud.githubusercontent.com/assets/10794297/20792724/57f2ce20-b7fe-11e6-824c-0b1dd2cb98b5.png)

**Comment by farizrahman4u** [comment]
@xiangyanchao  Cool!
Can you submit a pull request so that you will get proper github credits?

**Comment by minkyu119** [comment]
@xiangyanchao @farizrahman4u it's working well!!, thank you.

**Comment by InJokerPro** [comment]
I got rid of the error by removing all the foreslashes (or backslashes?) in the layer names.
