### ISSUE TITLE
Error on evaluating a model with dropout

### ISSUE THREAD

**Issue by ishalyminov** [farizrahman4u/seq2seq#127]
Here's some code just as in tests but with the evaluation step:

```
import numpy as np

from seq2seq.models import AttentionSeq2Seq

input_length = 10
input_dim = 2

output_length = 8
output_dim = 3

samples = 100

x = np.random.random((samples, input_length, input_dim))
y = np.random.random((samples, output_length, output_dim))
a = np.random.random((samples, input_length, input_dim))
b = np.random.random((samples, output_length, output_dim))

model = AttentionSeq2Seq(output_dim=output_dim, output_length=output_length, input_shape=(input_length, input_dim), dropout=0.1)
model.compile(loss='mse', optimizer='sgd')
model.fit(x, y, nb_epoch=1)
model.evaluate(a, b)
```

The evaluate step raises the following exception:

```
Traceback (most recent call last):
  File "test.py", line 21, in <module>
    model.evaluate(a, b)
  File "/home/is33/Envs/alexa_seq2seq/lib/python2.7/site-packages/keras/engine/training.py", line 1139, in evaluate
    self._make_test_function()
  File "/home/is33/Envs/alexa_seq2seq/lib/python2.7/site-packages/keras/engine/training.py", line 718, in _make_test_function
    **self._function_kwargs)
  File "/home/is33/Envs/alexa_seq2seq/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 727, in function
    return Function(inputs, outputs, updates=updates, **kwargs)
  File "/home/is33/Envs/alexa_seq2seq/lib/python2.7/site-packages/keras/backend/theano_backend.py", line 713, in __init__
    **kwargs)
  File "/home/is33/Envs/alexa_seq2seq/lib/python2.7/site-packages/theano/compile/function.py", line 320, in function
    output_keys=output_keys)
  File "/home/is33/Envs/alexa_seq2seq/lib/python2.7/site-packages/theano/compile/pfunc.py", line 479, in pfunc
    output_keys=output_keys)
  File "/home/is33/Envs/alexa_seq2seq/lib/python2.7/site-packages/theano/compile/function_module.py", line 1776, in orig_function
    output_keys=output_keys).create(
  File "/home/is33/Envs/alexa_seq2seq/lib/python2.7/site-packages/theano/compile/function_module.py", line 1428, in __init__
    accept_inplace)
  File "/home/is33/Envs/alexa_seq2seq/lib/python2.7/site-packages/theano/compile/function_module.py", line 177, in std_fgraph
    update_mapping=update_mapping)
  File "/home/is33/Envs/alexa_seq2seq/lib/python2.7/site-packages/theano/gof/fg.py", line 171, in __init__
    self.__import_r__(output, reason="init")
  File "/home/is33/Envs/alexa_seq2seq/lib/python2.7/site-packages/theano/gof/fg.py", line 360, in __import_r__
    self.__import__(variable.owner, reason=reason)
  File "/home/is33/Envs/alexa_seq2seq/lib/python2.7/site-packages/theano/gof/fg.py", line 474, in __import__
    r)
theano.gof.fg.MissingInputError: ("An input of the graph, used to compute Shape(<TensorType(float32, 3D)>), was not provided and not given a value.Use the Theano flag exception_verbosity='high',for more information on this error.", <TensorType(float32, 3D)>)
```

However, if you initialize AttentionSeq2Seq with `dropout=0.0`, everything works fine.

**Comment by farizrahman4u** [comment]
See #118
