### ISSUE TITLE
model.predict() for arbitrary number of sequences

### ISSUE THREAD

**Issue by nicolas-ivanov** [farizrahman4u/seq2seq#13]
After a successful model training goes prediction. Interestingly, current seq2seq implemenetation only lets you predict the same number of sequences as in your training batch... And in most cases I need a prediction only for one sequence at a time. Fix?

Code:
```python
import numpy as np
from keras.models import Sequential
from seq2seq.seq2seq import Seq2seq


vocab_size = 10 #number of words
seq_maxlen = 3 #length of input sequence and output sequence
embedding_dim = 5 #word embedding size
hidden_dim = 50 #memory size of seq2seq
batch_size = 7

seq2seq = Seq2seq(input_length=seq_maxlen,
                  input_dim=embedding_dim,
                  hidden_dim=hidden_dim,
                  output_dim=vocab_size,
                  output_length=seq_maxlen,
                  batch_size=batch_size,
                  depth=1)

print 'Build model ...'
model = Sequential()
model.add(seq2seq)
model.compile(loss='mse', optimizer='adam')

print 'Generate dummy train data ...'
train_examples_num = batch_size
X = np.zeros((train_examples_num, seq_maxlen, embedding_dim))
Y = np.zeros((train_examples_num, seq_maxlen, vocab_size))

for train_example_idx in xrange(train_examples_num):
    for word_idx in xrange(seq_maxlen):
        w2v_vector = np.random.rand(1, embedding_dim)[0]
        X[train_example_idx][word_idx] = w2v_vector

        bool_vector = np.zeros(vocab_size)
        bool_vector[np.random.choice(vocab_size)] = 1
        Y[train_example_idx][word_idx] = bool_vector

print X.shape, X
print Y.shape, Y

print 'Fit data ...'
model.fit(X, Y, batch_size=batch_size)

print 'Generate dummy predict data ...'
# predict_data = np.zeros((batch_size, seq_maxlen, embedding_dim))    # works this way
predict_data = np.zeros((1, seq_maxlen, embedding_dim))           # doesn't :(
for word_idx in xrange(seq_maxlen):
    w2v_vector = np.random.rand(1, embedding_dim)[0]
    predict_data[0][word_idx] = w2v_vector

print predict_data.shape, predict_data

model.predict(predict_data)
```
Log:
```
...
Generate dummy predict data ...
(1, 3, 5) [[[ 0.94333402  0.77712176  0.28421576  0.5250781   0.71062316]
  [ 0.40348298  0.18514321  0.42724825  0.30273698  0.70328719]
  [ 0.50133646  0.25419223  0.21284037  0.22480233  0.4796277 ]]]
Predict vectors ...
Traceback (most recent call last):
  File "/home/nicolas/Code/seq2seq/bin/try.py", line 53, in <module>
    print model.predict(predict_data)
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 499, in predict
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 257, in _predict_loop
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 606, in __call__
    storage_map=self.fn.storage_map)
  File "/usr/local/lib/python2.7/dist-packages/theano/compile/function_module.py", line 595, in __call__
    outputs = self.fn()
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan_op.py", line 672, in rval
    r = p(n, [x[0] for x in i], o)
  File "/usr/local/lib/python2.7/dist-packages/theano/scan_module/scan_op.py", line 661, in <lambda>
    self, node)
  File "scan_perform.pyx", line 356, in theano.scan_module.scan_perform.perform (/home/nicolas/.theano/compiledir_Linux-3.19--generic-x86_64-with-Ubuntu-15.04-vivid-x86_64-2.7.9-64/scan_perform/mod.cpp:3605)
  File "scan_perform.pyx", line 350, in theano.scan_module.scan_perform.perform (/home/nicolas/.theano/compiledir_Linux-3.19--generic-x86_64-with-Ubuntu-15.04-vivid-x86_64-2.7.9-64/scan_perform/mod.cpp:3537)
ValueError: Input dimension mis-match. (input[0].shape[0] = 1, input[1].shape[0] = 7)
Apply node that caused the error: Elemwise{mul,no_inplace}(<TensorType(int8, col)>, <TensorType(float64, matrix)>)
Inputs types: [TensorType(int8, col), TensorType(float64, matrix)]

Backtrace when the node is created:
  File "build/bdist.linux-x86_64/egg/seq2seq/lstm_encoder.py", line 94, in _step
    h_mask_tm1 = mask_tm1 * h_tm1

HINT: Use another linker then the c linker to have the inputs shapes and strides printed.
HINT: Use the Theano flag 'exception_verbosity=high' for a debugprint and storage map footprint of this apply node.
Apply node that caused the error: forall_inplace,cpu,scan_fn}(Elemwise{Composite{minimum(((i0 + i1) - i1), i2)}}.0, Subtensor{int64:int64:int8}.0, Subtensor{int64:int64:int8}.0, Subtensor{int64:int64:int8}.0, Subtensor{int64:int64:int8}.0, Elemwise{Cast{int8}}.0, IncSubtensor{InplaceSet;:int64:}.0, IncSubtensor{InplaceSet;:int64:}.0, <TensorType(float64, matrix)>, <TensorType(float64, matrix)>, <TensorType(float64, matrix)>, <TensorType(float64, matrix)>)
Inputs types: [TensorType(int64, scalar), TensorType(float64, 3D), TensorType(float64, 3D), TensorType(float64, 3D), TensorType(float64, 3D), TensorType(int8, (False, False, True)), TensorType(float64, 3D), TensorType(float64, 3D), TensorType(float64, matrix), TensorType(float64, matrix), TensorType(float64, matrix), TensorType(float64, matrix)]
Inputs shapes: [(), (3, 1, 50), (3, 1, 50), (3, 1, 50), (3, 1, 50), (3, 1, 1), (1, 7, 50), (1, 7, 50), (50, 50), (50, 50), (50, 50), (50, 50)]
Inputs strides: [(), (400, 400, 8), (400, 400, 8), (400, 400, 8), (400, 400, 8), (1, 1, 1), (2800, 400, 8), (2800, 400, 8), (400, 8), (400, 8), (400, 8), (400, 8)]
Inputs values: [array(3), 'not shown', 'not shown', 'not shown', 'not shown', array([[[0]],

       [[1]],

       [[1]]], dtype=int8), 'not shown', 'not shown', 'not shown', 'not shown', 'not shown', 'not shown']
```

**Comment by farizrahman4u** [comment]
This due to the presence of stateful RNNs. If your batch size is say,10, and you want to predict for say, 15 input sequence, simply make 2 batches, each of size 10. Fill the first batch with the first 10 inputs, and the second batch with the remaining 5 inputs and fill the rest of the second batch with zeros.

**Comment by nicolas-ivanov** [comment]
Gotcha, thanks
