### ISSUE TITLE
Seq2Seq model giving ValueError

### ISSUE THREAD

**Issue by wangtjwork** [farizrahman4u/seq2seq#132]
So here's my code, and I'm using an embedding layer before the actual model.

    model = Sequential()
    embedding_layer = Embedding(word_num,
                                EMBEDDING_DIM,
                                weights=[embedding_matrix],
                                input_length=MAX_SEQUENCE_LENGTH,
                                trainable=False)
    model.add(embedding_layer)

    import seq2seq
    from seq2seq.models import Seq2Seq

    model2 = Seq2Seq(input_length=MAX_SEQUENCE_LENGTH,input_dim=EMBEDDING_DIM, hidden_dim=HIDDEN_SIZE, output_length=44, output_dim=MAX_NB_WORDS + 1)
    model.add(model2)
    print model2.output_shape
    exit()`

Now when I try to see if that gives out the dimension I want, I get error like this:
Traceback (most recent call last):
  File "data_prepare.py", line 114, in <module>
    model2 = Seq2Seq(input_length=MAX_SEQUENCE_LENGTH,input_dim=EMBEDDING_DIM, hidden_dim=HIDDEN_SIZE, output_length=44, output_dim=MAX_NB_WORDS + 1)
  File "/Users/tianjianwang/anaconda/envs/tensorflow/lib/python2.7/site-packages/seq2seq/models.py", line 185, in Seq2Seq
    decoded_seq = decoder({'input': encoded_seq, 'ground_truth': inputs[1] if teacher_force else None, 'initial_readout': encoded_seq, 'states': states})
  File "build/bdist.macosx-10.6-x86_64/egg/recurrentshop/engine.py", line 569, in __call__
  File "/Users/tianjianwang/anaconda/envs/tensorflow/lib/python2.7/site-packages/keras/engine/topology.py", line 572, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/Users/tianjianwang/anaconda/envs/tensorflow/lib/python2.7/site-packages/keras/engine/topology.py", line 154, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors, mask=input_masks))
  File "build/bdist.macosx-10.6-x86_64/egg/recurrentshop/engine.py", line 328, in call
  File "build/bdist.macosx-10.6-x86_64/egg/recurrentshop/engine.py", line 51, in <lambda>
  File "/Users/tianjianwang/anaconda/envs/tensorflow/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1273, in rnn
    _step.output_size = int(_step(first_input, state)[0].get_shape()[-1])
  File "/Users/tianjianwang/anaconda/envs/tensorflow/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 1256, in _step
    output, new_states = step_function(input, states + constants)
  File "build/bdist.macosx-10.6-x86_64/egg/recurrentshop/engine.py", line 276, in step
  File "build/bdist.macosx-10.6-x86_64/egg/recurrentshop/engine.py", line 113, in _step
  File "/Users/tianjianwang/anaconda/envs/tensorflow/lib/python2.7/site-packages/seq2seq/cells.py", line 28, in step
    z = K.dot(x, W1) + K.dot(h_tm1, U) + b1
  File "/Users/tianjianwang/anaconda/envs/tensorflow/lib/python2.7/site-packages/keras/backend/tensorflow_backend.py", line 351, in dot
    out = tf.matmul(x, y)
  File "/Users/tianjianwang/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/math_ops.py", line 1398, in matmul
    name=name)
  File "/Users/tianjianwang/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1348, in _mat_mul
    transpose_b=transpose_b, name=name)
  File "/Users/tianjianwang/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/Users/tianjianwang/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2382, in create_op
    set_shapes_for_outputs(ret)
  File "/Users/tianjianwang/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1783, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/Users/tianjianwang/anaconda/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/framework/common_shapes.py", line 596, in call_cpp_shape_fn
    raise ValueError(err.message)
ValueError: Dimensions must be equal, but are 0 and 10001

10001 is the output dimension but what is that 0?

Any help appreciated

**Comment by farizrahman4u** [comment]
I am unable to reproduce this error. Are your libraries up to date?

**Comment by wangtjwork** [comment]
I'm using Python 2.7.12, 
Keras 1.1.1
Tensorflow 0.11.0rc2
RecurrentShop 0.01

**Comment by farizrahman4u** [comment]
Try with unroll=True. This is an issue with Keras's dynamic rnn for tensorflow

**Comment by wangtjwork** [comment]
Yeah its working now, thanks!
