### ISSUE TITLE
Keras core Layer couldn't find input_shape

### ISSUE THREAD

**Issue by wangtjwork** [farizrahman4u/seq2seq#134]
I'm now building a simple model, but there's a weird error coming out I couldn't handle.

```
model = Sequential()
embedding_layer = Embedding(word_num,
                            EMBEDDING_DIM,
                            weights=[embedding_matrix],
                            input_length=MAX_SEQUENCE_LENGTH,
                            trainable=False)

model.add(embedding_layer)

import seq2seq
from seq2seq.models import Seq2Seq

model2 = Seq2Seq(batch_input_shape=(16, MAX_SEQUENCE_LENGTH, EMBEDDING_DIM), hidden_dim=10, output_length=8, output_dim=20, depth=4, unroll = True)
model.add(model2)
print model2.output_shape
```

Now I'm getting an error like this:

```
Traceback (most recent call last):
  File "data_prepare.py", line 141, in <module>
    model2 = Seq2Seq(batch_input_shape=(16, MAX_SEQUENCE_LENGTH, EMBEDDING_DIM), hidden_dim=10, output_length=8, output_dim=20, depth=4, unroll = True)
  File "/Users/tianjianwang/anaconda/envs/tensorflow/lib/python2.7/site-packages/seq2seq/models.py", line 179, in Seq2Seq
    encoded_seq = dense2(encoded_seq)
  File "/Users/tianjianwang/anaconda/envs/tensorflow/lib/python2.7/site-packages/keras/engine/topology.py", line 487, in __call__
    self.build(input_shapes[0])
  File "/Users/tianjianwang/anaconda/envs/tensorflow/lib/python2.7/site-packages/keras/layers/core.py", line 689, in build
    assert len(input_shape) == 2
TypeError: object of type 'NoneType' has no len()
```

using newest version of Keras 1.1.1 and tensor flow 0.11, and have set the "unroll" parameter to True.

Seemed to be working 2 days ago but is not working now again. Dunno why. Perhaps a silly mistake of mine. Anyway please help.

Thank you!

**Comment by farizrahman4u** [comment]
Can not reproduce this error on latest versions keras, recurrentshop and seq2seq.
Try updating all.
