### ISSUE TITLE
Shapes must be equal rank,but are 0 and 1

### ISSUE THREAD

**Issue by sherlockhoatszx** [farizrahman4u/seq2seq#147]
Hi 
#### backgroud information: 
- [ ] software:use keras, tensorflow backened,python2.7. seq2seq package.   
- [ ] what i want to do( the prupose of the project): try to make time series prediction and consider the input and out as sequences. My previous solution is try to use BiLSTM and TimeDistributed Dense structure to predict. but the result not good if the predict unit extend a long time unit, the next 48 hours prediction for per hour ,for example.
#### code snippt:
- [ ] input sequences dimension: nb_samples = 100,  seq_length = 1, feature_length = 30. 
- [ ] output sequences dimension: nb_samples =1, seq_len=1,feature_length = 30 .
- [ ] and build the model as blow:
```

models = []
output_dim = 1
output_length = feature_length
models += [AttentionSeq2Seq(output_dim=output_dim, output_length=output_length,unroll=True, input_shape=(seq_length,feature_length))]
models += [AttentionSeq2Seq(output_dim=output_dim, output_length=output_length,unroll=True, input_shape=(seq_length,feature_length), depth=2)]
models += [AttentionSeq2Seq(output_dim=output_dim, output_length=output_length, unroll=True,input_shape=(seq_length,feature_length), depth=3)]

for model in models:
     model.compile(loss='mse', optimizer='sgd')
     model.fit(train_X ,train_Y, nb_epoch=1)
y_predict = model.predict(predict_range)
```

###Error report : 
Shapes must be equal rank, but are 0 and 1
more details:

Traceback (most recent call last):
  File "seq2seq_attentionlstm_day_pred.py", line 332, in <module>
    y_true,y_pred,error_estimate = op(datapath,val_data_len,data_shifts)
  File "seq2seq_attentionlstm_day_pred.py", line 219, in op
    models += [AttentionSeq2Seq(output_dim=output_dim, output_length=output_length,unroll=True, input_shape=(seq_length,feature_length))]
  File "/usr/local/lib/python2.7/dist-packages/seq2seq/models.py", line 274, in AttentionSeq2Seq
    decoded = decoder(encoded)
  File "/usr/local/lib/python2.7/dist-packages/recurrentshop/engine.py", line 569, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 572, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 149, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/usr/local/lib/python2.7/dist-packages/recurrentshop/engine.py", line 316, in call
    initial_states = self.get_initial_states(x)
  File "/usr/local/lib/python2.7/dist-packages/recurrentshop/engine.py", line 383, in get_initial_states
    input = layer._step(input, layer_initial_states)[0]
  File "/usr/local/lib/python2.7/dist-packages/recurrentshop/engine.py", line 113, in _step
    return self.step(*args)
  File "/usr/local/lib/python2.7/dist-packages/seq2seq/cells.py", line 85, in step
    x = K.batch_dot(energy, H, axes=(1, 1))
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 401, in batch_dot
    out = tf.batch_matmul(x, y, adj_x=adj_x, adj_y=adj_y)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 368, in _batch_mat_mul
    adj_y=adj_y, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2382, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1783, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/common_shapes.py", line 596, in call_cpp_shape_fn
    raise ValueError(err.message)
ValueError: Shapes must be equal rank, but are 0 and 1

**Comment by ErmiaAzarkhalili** [comment]
Hi @farizrahman4u 
in your speed_test.py file there is some serious errors which makde this example useless...
Could you please resolve them and let us utilize your great package?
