### ISSUE TITLE
TypeError: __int__ returned non-int (type NoneType)

### ISSUE THREAD

**Issue by krywykj** [farizrahman4u/seq2seq#149]
Hi,

I work on a Ubuntu 16:04.

When I run the first code of this tutorial seq2seq : 

```
import seq2seq
from seq2seq.models import SimpleSeq2Seq
model = SimpleSeq2Seq(input_dim=5, hidden_dim=10, output_length=8, output_dim=8)
model.compile(loss='mse', optimizer='rmsprop')
```

 I have the following error : 

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-44-84d868dfe1d5> in <module>()
      2 from seq2seq.models import SimpleSeq2Seq
      3 
----> 4 model = SimpleSeq2Seq(input_dim=5, hidden_dim=10, output_length=8, output_dim=8)
      5 model.compile(loss='mse', optimizer='rmsprop')

/home/krywyk/anaconda2/lib/python2.7/site-packages/seq2seq-0.1.0-py2.7.egg/seq2seq/models.pyc in SimpleSeq2Seq(output_dim, output_length, hidden_dim, depth, dropout, **kwargs)
     83         model = Sequential()
     84         model.add(encoder)
---> 85         model.add(decoder)
     86         return model
     87 

/home/krywyk/anaconda2/lib/python2.7/site-packages/keras/models.pyc in add(self, layer)
    310                  output_shapes=[self.outputs[0]._keras_shape])
    311         else:
--> 312             output_tensor = layer(self.outputs[0])
    313             if type(output_tensor) is list:
    314                 raise Exception('All layers in a Sequential model '

/home/krywyk/anaconda2/lib/python2.7/site-packages/recurrentshop-0.0.1-py2.7.egg/recurrentshop/engine.pyc in __call__(self, x, mask)
    569                                 break
    570                 if inbound_layers:
--> 571                         self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
    572                         input_added = True
    573                 if input_added:

/home/krywyk/anaconda2/lib/python2.7/site-packages/keras/engine/topology.pyc in add_inbound_node(self, inbound_layers, node_indices, tensor_indices)
    570         # creating the node automatically updates self.inbound_nodes
    571         # as well as outbound_nodes on inbound layers.
--> 572         Node.create_node(self, inbound_layers, node_indices, tensor_indices)
    573 
    574     def get_output_shape_for(self, input_shape):

/home/krywyk/anaconda2/lib/python2.7/site-packages/keras/engine/topology.pyc in create_node(cls, outbound_layer, inbound_layers, node_indices, tensor_indices)
    147 
    148         if len(input_tensors) == 1:
--> 149             output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
    150             output_masks = to_list(outbound_layer.compute_mask(input_tensors[0], input_masks[0]))
    151             # TODO: try to auto-infer shape if exception is raised by get_output_shape_for

/home/krywyk/anaconda2/lib/python2.7/site-packages/recurrentshop-0.0.1-py2.7.egg/recurrentshop/engine.pyc in call(self, x, mask)
    326                                 states = [K.in_train_phase(states_1[i], states_0[i]) for i in range(len(states_0))]
    327                         else:
--> 328                                 last_output, outputs, states, updates = rnn(self.step, K.zeros((1, self.output_length, 1)), initial_states, unroll=unroll, input_length=self.output_length)
    329                 else:
    330                         if self.uses_learning_phase:

/home/krywyk/anaconda2/lib/python2.7/site-packages/recurrentshop-0.0.1-py2.7.egg/recurrentshop/engine.pyc in <lambda>(*args, **kwargs)
     49         rnn = backend.rnn
     50 else:
---> 51         rnn = lambda *args, **kwargs: list(K.rnn(*args, **kwargs)) + [[]]
     52 
     53 

/home/krywyk/anaconda2/lib/python2.7/site-packages/keras/backend/tensorflow_backend.pyc in rnn(step_function, inputs, initial_states, go_backwards, mask, constants, unroll, input_length)
   1200             state_size = state.get_shape()[-1]
   1201         else:
-> 1202             state_size = int(states[0].get_shape()[-1])
   1203             if nb_states == 1:
   1204                 state = states[0]

TypeError: __int__ returned non-int (type NoneType)

```

Someone knows how to fix it ?

Best wishes for the holliday season.

**Comment by farizrahman4u** [comment]
Tried with unroll=True?
```python
model = SimpleSeq2Seq(input_dim=5, hidden_dim=10, output_length=8, output_dim=8, unroll=True)
```

**Comment by yuzhipeng588** [comment]
I have similar problem and after I tried:
`model = SimpleSeq2Seq(input_dim=5, hidden_dim=10, output_length=8, output_dim=8, unroll=True)`
I got error:

  File "<ipython-input-8-3e2e5dff10b7>", line 1, in <module>
    model = SimpleSeq2Seq(input_dim=5, hidden_dim=10, output_length=8, output_dim=8, unroll=True)

  File "//anaconda/lib/python3.5/site-packages/seq2seq-0.1.0-py3.5.egg/seq2seq/models.py", line 64, in SimpleSeq2Seq
    encoder = RecurrentContainer(unroll=unroll, stateful=stateful, input_length=shape[1])

  File "//anaconda/lib/python3.5/site-packages/recurrentshop-0.0.1-py3.5.egg/recurrentshop/engine.py", line 185, in __init__
    assert input_length, 'Missing argument: input_length should be specified for unrolling.'

AssertionError: Missing argument: input_length should be specified for unrolling.

How to fix this?

**Comment by yuzhipeng588** [comment]
Figure it out. Just add an arguement 'input_length'
