### ISSUE TITLE
Attention seq2seq example does not work

### ISSUE THREAD

**Issue by rmeertens** [farizrahman4u/seq2seq#153]
Hey everybody, 

I'm trying to use the AttentionSeq2Seq layer as given in the example, but I get an error. 
Although I tried debugging it and finding the problem myself without success so far. Anybody knows what I'm doing wrong?

Kind regards,

>> import seq2seq
>>> from seq2seq.models import AttentionSeq2Seq
>>> model = AttentionSeq2Seq(input_dim=5, input_length=7, hidden_dim=10, output_length=8, output_dim=20, depth=4)
/usr/local/lib/python3.4/dist-packages/keras/engine/topology.py:376: UserWarning: The `regularizers` property of layers/models is deprecated. Regularization losses are now managed via the `losses` layer/model property.
  warnings.warn('The `regularizers` property of layers/models '
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/keras/backend/tensorflow_backend.py", line 871, in batch_dot
    out = tf.batch_matmul(x, y, adj_a=adj_x, adj_b=adj_y)
TypeError: _batch_mat_mul() got an unexpected keyword argument 'adj_a'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/tensor_shape.py", line 563, in merge_with
    self.assert_same_rank(other)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/tensor_shape.py", line 609, in assert_same_rank
    "Shapes %s and %s must have the same rank" % (self, other))
ValueError: Shapes () and (?,) must have the same rank

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/seq2seq-0.1.0-py3.4.egg/seq2seq/models.py", line 283, in AttentionSeq2Seq
  File "/usr/local/lib/python3.4/dist-packages/recurrentshop-0.0.1-py3.4.egg/recurrentshop/engine.py", line 571, in __call__
  File "/usr/local/lib/python3.4/dist-packages/keras/engine/topology.py", line 632, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python3.4/dist-packages/keras/engine/topology.py", line 164, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/usr/local/lib/python3.4/dist-packages/recurrentshop-0.0.1-py3.4.egg/recurrentshop/engine.py", line 316, in call
  File "/usr/local/lib/python3.4/dist-packages/recurrentshop-0.0.1-py3.4.egg/recurrentshop/engine.py", line 383, in get_initial_states
  File "/usr/local/lib/python3.4/dist-packages/recurrentshop-0.0.1-py3.4.egg/recurrentshop/engine.py", line 113, in _step
  File "/usr/local/lib/python3.4/dist-packages/seq2seq-0.1.0-py3.4.egg/seq2seq/cells.py", line 85, in step
  File "/usr/local/lib/python3.4/dist-packages/keras/backend/tensorflow_backend.py", line 873, in batch_dot
    out = tf.batch_matmul(x, y, adj_x=adj_x, adj_y=adj_y)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/gen_math_ops.py", line 390, in _batch_mat_mul
    adj_y=adj_y, name=name)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/op_def_library.py", line 703, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 2319, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/ops.py", line 1711, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/ops/math_ops.py", line 1557, in _BatchMatMulShape
    batch_dims = a_shape[:-2].merge_with(b_shape[:-2])
  File "/usr/local/lib/python3.4/dist-packages/tensorflow/python/framework/tensor_shape.py", line 570, in merge_with
    (self, other))
ValueError: Shapes () and (?,) are not compatible

**Comment by rmeertens** [comment]
Also, 
looks like it is going wrong at line 85 in models: 
File "/usr/local/lib/python3.4/dist-packages/seq2seq-0.1.0-py3.4.egg/seq2seq/cells.py", line 85, in step
File "/usr/local/lib/python3.4/dist-packages/keras/backend/tensorflow_backend.py", line 873, in batch_dot
out = tf.batch_matmul(x, y, adj_x=adj_x, adj_y=adj_y)

Although I can't really see what would be wrong with this batch_dot...

**Comment by rmeertens** [comment]
Created a clean conda environment and pip installed all dependencies (so tensorflow 0.10). This still does not work. Tried with a Theano backend, this works :D

**Comment by farizrahman4u** [comment]
unroll=True when on tensorflow.
