### ISSUE TITLE
AttributeError: 'list' object has no attribute 'shape'

### ISSUE THREAD

**Issue by nicolas-ivanov** [farizrahman4u/seq2seq#16]
`model.save_weights()` doesn't work.

Code:
```python
import numpy as np
from keras.models import Sequential
from seq2seq.seq2seq import Seq2seq


vocab_size = 10 #number of words
maxlen = 3 #length of input sequence and output sequence
embedding_dim = 5 #word embedding size
hidden_dim = 50 #memory size of seq2seq
batch_size = 7

seq2seq = Seq2seq(input_length=maxlen,
                  input_dim=embedding_dim,
                  hidden_dim=hidden_dim,
                  output_dim=vocab_size,
                  output_length=maxlen,
                  batch_size=batch_size,
                  depth=1)

print 'Build model ...'
model = Sequential()
model.add(seq2seq)
model.compile(loss='mse', optimizer='adam')

model_full_path = "./saved_model.pkl"
model.save_weights(model_full_path, overwrite=True)
```

Log:
```
Traceback (most recent call last):
  File "/home/nicolas/Code/seq2seq/bin/try.py", line 26, in <module>
    model.save_weights(model_full_path, overwrite=True)
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 555, in save_weights
AttributeError: 'list' object has no attribute 'shape'
```

**Comment by farizrahman4u** [comment]
Fixed!
