### ISSUE TITLE
ImportError:cannot import name _collect_previous_mask

### ISSUE THREAD

**Issue by srijanie** [farizrahman4u/seq2seq#177]
Traceback (most recent call last):
  File "ss.py", line 1, in <module>
    import seq2seq
  File "/Users/Swadesh/anaconda/lib/python2.7/site-packages/seq2seq/__init__.py", line 1, in <module>
    from .cells import *
  File "/Users/Swadesh/anaconda/lib/python2.7/site-packages/seq2seq/cells.py", line 1, in <module>
    from recurrentshop import RNNCell, LSTMCell, weight
  File "build/bdist.macosx-10.7-x86_64/egg/recurrentshop/__init__.py", line 1, in <module>
  File "build/bdist.macosx-10.7-x86_64/egg/recurrentshop/engine.py", line 5, in <module>
ImportError: cannot import name _collect_previous_mask

This is the problem I am facing. Previously there was a similar error for "initializers", because I am using Keras 1.2.2 and it accepts "initializations". Is the current error because of the version of Keras, or is it something else?

Thanks in advance for your help.

**Comment by cemheren** [comment]
you would need to update to keras 2.0
