### ISSUE TITLE
How to encode input

### ISSUE THREAD

**Issue by dhrushilbadani** [farizrahman4u/seq2seq#181]
Hi, I've trained a Seq2seq `model` that takes a `(n, 53, 1024)` input (n is the # of examples) and encodes each of the n examples into a 1024-dimensional vector i.e. the total size of the output is `(n, 1024)`. I wanted to use it to encode my data `X` (10000, 53, 1024) as follows:

```
# model is Seq2Seq initialized with batch_input_shape = (32, 53, 1024)
input_layer = Input(shape=(53, 1024))
encode_layer = model.encoder(input_layer)
encoder = Model(input_layer, encode_layer)
# X is of shape (10000, 53, 1024)
X_encoded = encoder.predict(X)
```

I get the following error:
```
Traceback (most recent call last):
  File "train_classifier.py", line 38, in <module>
    encode_layer = model.encoder(input_layer)
  File "build/bdist.linux-x86_64/egg/recurrentshop/engine.py", line 549, in __call__
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 493, in assert_input_compatibility
    str(x_shape))
ValueError: Input 0 is incompatible with layer recurrentcontainer_1: expected shape=(32, 53, 1024), found shape=(None, 53, 1024)
```

What should I do? Thanks :)

**Comment by michaelcapizzi** [comment]
I'd like to "bump" this issue as I have the same question.

Anyone with any insight?

**Comment by michaelcapizzi** [comment]
Made a bit of progress.  See my comment here: https://github.com/farizrahman4u/seq2seq/issues/143

**Comment by timothy-wong** [comment]
I've managed to get the encoder output (context vector) using K backend.

Code is in this thread: [Context vector at each time step](https://github.com/farizrahman4u/seq2seq/issues/178)
