### ISSUE TITLE
Got error when 'from recurrentshop.cells import *' 

### ISSUE THREAD

**Issue by r06945003** [farizrahman4u/seq2seq#233]
----> 2 from recurrentshop.cells import *
ModuleNotFoundError: No module named 'recurrentshop.cells'

There is no error with import recurrentshop. How can I fix it? Thank you.

keras: 2.0.8
python: 3.6.1

**Comment by starbaby01** [comment]
I also get this errer, how solve it?

**Comment by matteodelucchi** [comment]
Same error here:

`In [1]: import seq2seq
Traceback (most recent call last):

  File "<ipython-input-26-c3facfb0245c>", line 1, in <module>
    import seq2seq

  File "/usr/local/lib/python3.6/dist-packages/seq2seq/__init__.py", line 1, in <module>
    from .cells import *

  File "/usr/local/lib/python3.6/dist-packages/seq2seq/cells.py", line 2, in <module>
    from recurrentshop.cells import *

ModuleNotFoundError: No module named 'recurrentshop.cells'`


and in the module `cells.py` of recurrentshop:

`In [2]: import recurrentshop
In [3]: from recurrentshop.cells import *
Traceback (most recent call last):

  File "<ipython-input-32-22dd736f938f>", line 2, in <module>
    from recurrentshop.cells import *

ModuleNotFoundError: No module named 'recurrentshop.cells'`

**Comment by onitaiji** [comment]
Also, same error:

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-59-a0d36cfad084> in <module>()
      2 from keras.layers import Input, Embedding, Dense
      3 from keras.utils import plot_model
----> 4 from seq2seq import Seq2Seq
      5 
      6 lstm_size = embedding_dimension * 2

/usr/local/lib/python3.6/dist-packages/seq2seq/__init__.py in <module>()
----> 1 from .cells import *
      2 from .models import *

/usr/local/lib/python3.6/dist-packages/seq2seq/cells.py in <module>()
      1 import recurrentshop
----> 2 from recurrentshop.cells import *
      3 from keras.models import Model
      4 from keras.layers import Input, Dense, Lambda, Activation
      5 from keras.layers import add, multiply, concatenate

ModuleNotFoundError: No module named 'recurrentshop.cells'
