### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by qfzhu** [farizrahman4u/seq2seq#25]
Hi, thanks for sharing the great code. I met an error when using the AttentionSeq2seq model.The error information:

Traceback (most recent call last):
  File "train.py", line 182, in <module>
    model.compile(loss='mse', optimizer='adam')
  File "build/bdist.linux-x86_64/egg/keras/models.py", line 467, in compile
  File "build/bdist.linux-x86_64/egg/keras/optimizers.py", line 250, in get_updates
  File "build/bdist.linux-x86_64/egg/keras/optimizers.py", line 47, in get_gradients
  File "build/bdist.linux-x86_64/egg/keras/backend/theano_backend.py", line 402, in gradients
  File "/users2/qfzhu/anaconda/lib/python2.7/site-packages/theano/gradient.py", line 545, in grad
    grad_dict, wrt, cost_name)
  File "/users2/qfzhu/anaconda/lib/python2.7/site-packages/theano/gradient.py", line 1283, in _populate_grad_dict
    rval = [access_grad_cache(elem) for elem in wrt]
  File "/users2/qfzhu/anaconda/lib/python2.7/site-packages/theano/gradient.py", line 1241, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/users2/qfzhu/anaconda/lib/python2.7/site-packages/theano/gradient.py", line 951, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
  File "/users2/qfzhu/anaconda/lib/python2.7/site-packages/theano/gradient.py", line 1241, in access_grad_cache
    term = access_term_cache(node)[idx]
  File "/users2/qfzhu/anaconda/lib/python2.7/site-packages/theano/gradient.py", line 951, in access_term_cache
    output_grads = [access_grad_cache(var) for var in node.outputs]
...
...
 
  File "/users2/qfzhu/anaconda/lib/python2.7/site-packages/theano/scan_module/scan_utils.py", line 1030, in local_traverse
    rval += local_traverse(inp, x)
  File "/users2/qfzhu/anaconda/lib/python2.7/site-packages/theano/scan_module/scan_utils.py", line 1030, in local_traverse
    rval += local_traverse(inp, x)
  File "/users2/qfzhu/anaconda/lib/python2.7/site-packages/theano/scan_module/scan_utils.py", line 1030, in local_traverse
    rval += local_traverse(inp, x)
  File "/users2/qfzhu/anaconda/lib/python2.7/site-packages/theano/scan_module/scan_utils.py", line 1030, in local_traverse
    rval += local_traverse(inp, x)
  File "/users2/qfzhu/anaconda/lib/python2.7/site-packages/theano/scan_module/scan_utils.py", line 1023, in local_traverse
    if equal_computations([graph], [x]):
  File "/users2/qfzhu/anaconda/lib/python2.7/site-packages/theano/scan_module/scan_utils.py", line 410, in equal_computations
    if x not in in_xs and x.type != y.type:
  File "/users2/qfzhu/anaconda/lib/python2.7/site-packages/theano/gof/utils.py", line 127, in __ne__
    return not self == other
  File "/users2/qfzhu/anaconda/lib/python2.7/site-packages/theano/tensor/type.py", line 260, in __eq__
    return type(self) == type(other) and other.dtype == self.dtype \
RuntimeError: maximum recursion depth exceeded while calling a Python object

When I use the Seq2seq layer, the model works well. However when i changes to the AttentionSeq2seq layer, i meet this error.Here is my model with AttentionSeq2seq:

model = Sequential()
model.add(embeddings.Embedding(input_dim=len(chars)+1, output_dim=EMB_DIM, input_length=MAXLEN))
seq2seq = AttentionSeq2seq(input_dim=EMB_DIM, input_length=MAXLEN, hidden_dim=HIDDEN_SIZE, output_length=MAXLEN, output_dim=len(chars), depth=1)
model.add(seq2seq)
model.compile(loss='mse', optimizer='adam')

And I am using the keras=0.3.1, numpy=1.10.4, seq2seq=0.0.2

Besides, I changed the parameter "masking=False" to "mask=None" in the decoders.py, due to an unexpected param error, I don't know if it is the reason of the error mentioned before.

Thanks a lot

**Comment by farizrahman4u** [comment]
Add this to your code:

```python
import sys
sys.setrecursionlimit(100000)
```

**Comment by qfzhu** [comment]
Thanks for your quick reply. I have tried that method with  `sys.setrecursionlimit(10000)`before and got the same error. Now I add the limit up to 100000 as your advised, and the model has been run more than 2 hours, but still not finish building, may be there is something other going wrong ?

**Comment by farizrahman4u** [comment]
Should be a theano bug. I  will come up  with a workaround soon. Its because of the nested theano.scan in attention layer I think.

**Comment by qfzhu** [comment]
Thanks for reply. Hope it can be fixed in near future :-)

**Comment by farizrahman4u** [comment]
The model compiles for me. Can you provide the values for `EMB_DIM`, `HIDDEN_SIZE`, `MAXLEN` and `len(chars)` ?

**Comment by qfzhu** [comment]
here is the values:`EMB_DIM = 300`,`HIDDEN_SIZE = 1000`,`len(chars)=1408`,`MAXLEN=10`

**Comment by qfzhu** [comment]
Hi, I find the problem lies in the `len(chars)`. For my program, it is the total number of  characters of the training set, now my model can run on a pretty small data set, whose `len(chars)=100` . Any advise for big data set with `len(chars)=1000` or even more.

**Comment by farizrahman4u** [comment]
I usually add a convolution layer on top to reduce the sequence length when building char-level models.
