### ISSUE TITLE
Issue with SoftShuffle

### ISSUE THREAD

**Issue by meain** [farizrahman4u/seq2seq#27]
Could not compile the model

```python
    model = SoftShuffle(input_dim = 1, input_length = 10)
    model.compile(loss='mse', optimizer='rmsprop')
```

Traceback (most recent call last):
  File "s2.py", line 13, in <module>
    model.compile(loss='mse', optimizer='rmsprop')
  File "build/bdist.macosx-10.6-intel/egg/keras/models.py", line 372, in compile
  File "build/bdist.macosx-10.6-intel/egg/seq2seq/models.py", line 286, in get_output
NameError: global name 'T' is not defined

**Comment by farizrahman4u** [comment]
Fixed. This layer is used for sorting etc. btw.
