### ISSUE TITLE
error:name 'K' is not defined

### ISSUE THREAD

**Issue by fsdfsd123** [farizrahman4u/seq2seq#276]
afte i use sudo pip install git+https://github.com/farizrahman4u/seq2seq.git,I write import seq2seq in python command line , but i meet this bug:

Using TensorFlow backend.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/shawn/anaconda3/lib/python3.7/site-packages/seq2seq-1.0.0-py3.7.egg/seq2seq/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/shawn/anaconda3/lib/python3.7/site-packages/seq2seq-1.0.0-py3.7.egg/seq2seq/cells.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/shawn/anaconda3/lib/python3.7/site-packages/recurrentshop-1.0.0-py3.7.egg/recurrentshop/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 668, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 638, in _load_backward_compatible
  File "/Users/shawn/anaconda3/lib/python3.7/site-packages/recurrentshop-1.0.0-py3.7.egg/recurrentshop/engine.py", line 10, in <module>
NameError: name 'K' is not defined

How can i solve this? thank u

**Comment by snoofalus** [comment]
Have the same issue, think its because of changes to keras backend.

**Comment by zhunipingan** [comment]
I meet the same error, do you know the solution now, If have, please share me the answer, thanks!

**Comment by absognety** [comment]
https://github.com/farizrahman4u/seq2seq/issues/165#issuecomment-365166504 

Install `seq2seq.py` by doing installations as mentioned in above issue:
1. recurrentshop
2. seq2seq

If you face a bug as `name K is not defined`:
Fix this using https://github.com/farizrahman4u/seq2seq/issues/165#issuecomment-583959642
