### ISSUE TITLE
Bug in SoftShuffle layer

### ISSUE THREAD

**Issue by meain** [farizrahman4u/seq2seq#29]
model : 

```python
model = SoftShuffle(input_dim = 1, input_length = 10)
model.compile(loss='mse', optimizer='rmsprop')
```

Traceback (most recent call last):
  File "s2.py", line 13, in <module>
    model.compile(loss='mse', optimizer='rmsprop')
  File "build/bdist.macosx-10.6-intel/egg/keras/models.py", line 418, in compile
  File "build/bdist.macosx-10.6-intel/egg/keras/backend/theano_backend.py", line 361, in function
  File "build/bdist.macosx-10.6-intel/egg/keras/backend/theano_backend.py", line 354, in __init__
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/compile/function.py", line 266, in function
    profile=profile)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/compile/pfunc.py", line 511, in pfunc
    on_unused_input=on_unused_input)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/compile/function_module.py", line 1466, in orig_function
    defaults)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/compile/function_module.py", line 1324, in create
    input_storage=input_storage_lists)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/gof/link.py", line 519, in make_thunk
    output_storage=output_storage)[:3]
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/gof/vm.py", line 897, in make_all
    no_recycling))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/scan_module/scan_op.py", line 637, in make_thunk
    import scan_perform_ext
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/theano/scan_module/scan_perform_ext.py", line 133, in <module>
    from scan_perform.scan_perform import *
  File "numpy.pxd", line 155, in init theano.scan_module.scan_perform (/Users/abinsimon/.theano/compiledir_Darwin-14.3.0-x86_64-i386-64bit-i386-2.7.10-64/scan_perform/mod.cpp:7672)
ValueError: ('The following error happened while compiling the node', forall_inplace,cpu,scan_fn&scan_fn}(Shape_i{1}.0, Subtensor{int64:int64:int8}.0, IncSubtensor{InplaceSet;:int64:}.0, DeepCopyOp.0, IncSubtensor{InplaceSet;:int64:}.0, IncSubtensor{InplaceSet;:int64:}.0, Shape_i{1}.0, Shape_i{1}.0, <TensorType(float32, matrix)>, <TensorType(float32, vector)>, <TensorType(float32, matrix)>, <TensorType(float32, matrix)>, <TensorType(float32, vector)>, <TensorType(float32, matrix)>, <TensorType(float32, matrix)>, <TensorType(float32, vector)>, <TensorType(float32, matrix)>, <TensorType(float32, matrix)>, <TensorType(float32, vector)>, <TensorType(float32, matrix)>, InplaceDimShuffle{x,0}.0, InplaceDimShuffle{x,0}.0, InplaceDimShuffle{x,0}.0, InplaceDimShuffle{x,0}.0), '\n', 'numpy.dtype has the wrong size, try recompiling')

**Comment by meain** [comment]
Sorry, it was a theano error. Fixed on reinstalling theano.
