### ISSUE TITLE
Attention model and masking

### ISSUE THREAD

**Issue by mbollmann** [farizrahman4u/seq2seq#44]
I've noticed that the attention-based model doesn't seem to be working with input masking:

```python
model = Sequential()                                                                                                  
model.add(Embedding(10, 4, input_length=12, mask_zero=mask_zero))                                                         
s2s = AttentionSeq2seq(input_dim=4, input_length=12, hidden_dim=16, output_length=13, output_dim=11, depth=2)         
model.add(s2s)                                                                                                        
model.compile(loss='mse', optimizer='rmsprop') 
```

This simplified model compiles fine with `mask_zero=False`, but gives a cryptic Theano error with `mask_zero=True`:

```
[...]
  File "/lib/python3.4/site-packages/theano/tensor/elemwise.py", line 146, in __init__
    (i, j, len(input_broadcastable)))
ValueError: new_order[2] is 2, but the input only has 2 axes.
```

Is this a bug, or is masking simply not possible with the attention-based model? I admit I didn't dive deeply into the theory of that model yet, but if masking is generally not possible with it, may I suggest adding a note to the README for other unwary experimenters like me? :)

**Comment by mbollmann** [comment]
So I spent more time on this, and it seems it all comes down to the Bidirectional layer, which explicitly contains code to deal with input masking. I also found various discussions on the Keras repo about this (e.g. https://github.com/fchollet/keras/pull/1282) but have a hard time following it all.

In short, this code ...

```python
from keras.models import Sequential
from keras.layers.recurrent import LSTM
from keras.layers.embeddings import Embedding
from seq2seq.layers.bidirectional import Bidirectional

model = Sequential()
model.add(Embedding(10, 4, input_length=12, mask_zero=True))
model.add(Bidirectional(LSTM(11, return_sequences=True)))
model.compile(loss='mse', optimizer='rmsprop')
```

... produces this exception for me:

```
Traceback (most recent call last):
  File "test-bidirectional.py", line 13, in <module>
    model.compile(loss='mse', optimizer='rmsprop')
  File "/lib/python3.4/site-packages/keras/models.py", line 499, in compile
    self.y_train = self.get_output(train=True)
  File "/lib/python3.4/site-packages/keras/layers/containers.py", line 110, in get_output
    return self.layers[-1].get_output(train)
  File "/lib/python3.4/site-packages/seq2seq/layers/bidirectional.py", line 89, in get_output
    mask_rev = reverse(mask) if mask else None # 1,1,1,1,0,0,0
  File "/lib/python3.4/site-packages/seq2seq/layers/bidirectional.py", line 84, in reverse
    rev = K.permute_dimensions(x, (1, 0, 2))[::-1]
  File "/lib/python3.4/site-packages/keras/backend/theano_backend.py", line 239, in permute_dimensions
    return x.dimshuffle(pattern)
  File "/lib/python3.4/site-packages/theano/tensor/var.py", line 360, in dimshuffle
    pattern)
  File "/lib/python3.4/site-packages/theano/tensor/elemwise.py", line 146, in __init__
    (i, j, len(input_broadcastable)))
ValueError: new_order[2] is 2, but the input only has 2 axes.
```

... which seems to be explicitly about the code that handles the masking.

Any hint about whether that's a bug or if I'm doing something wrong would be appreciated.

**Comment by htw2012** [comment]
I also get the problem like ValueError: new_order[2] is 2, but the input only has 2 axes.
Do you solve this problem?
