### ISSUE TITLE
Error while using Seq2seq model

### ISSUE THREAD

**Issue by manzilzaheer** [farizrahman4u/seq2seq#53]
If I try to execute the example given in introduction

```python
import seq2seq
from seq2seq.models import Seq2seq

model = Seq2seq(batch_input_shape=(16, 7, 5), hidden_dim=10, output_length=8, output_dim=20, depth=4)
model.compile(loss='mse', optimizer='rmsprop')
```

then I get the following error:

 ```bash
Traceback (most recent call last):
  File "/export/home/manzil/PycharmProjects/autoencoder/main.py", line 8, in <module>
    model2.compile(loss='mse', optimizer='rmsprop')
  File "/export/home/manzil/.local/lib/python2.7/site-packages/Keras-0.3.2-py2.7.egg/keras/models.py", line 507, in compile
    self.y_train = self.get_output(train=True)
  File "/export/home/manzil/.local/lib/python2.7/site-packages/Keras-0.3.2-py2.7.egg/keras/layers/containers.py", line 130, in get_output
    return self.layers[-1].get_output(train)
  File "/export/home/manzil/PycharmProjects/autoencoder/seq2seq/layers/decoders.py", line 151, in get_output
    x_t = self.get_input(train)
  File "/export/home/manzil/.local/lib/python2.7/site-packages/Keras-0.3.2-py2.7.egg/keras/layers/core.py", line 241, in get_input
    previous_output = self.previous.get_output(train=train)
  File "/export/home/manzil/PycharmProjects/autoencoder/seq2seq/layers/state_transfer_lstm.py", line 36, in get_output
    assert K.ndim(X) == 3 #, 'Input should be at least 3D.'
AssertionError
```

I tried with latest version of Keras as well as the version 0.3.2 in PiPy.

Any pointers would be very helpful.

**Comment by elephantgcc** [comment]
I also meet with this problem.
@mathewlee11 , do you have some progress?
@farizrahman4u , we need your help!

**Comment by farizrahman4u** [comment]
Will update Seq2seq to match with latest keras soon.

**Comment by manzilzaheer** [comment]
@farizrahman4u If you can provide me a little hints on what things needs to be updated, I can try and create a pull request. 
Currently it seems output size from first encoder doesn't match anything after it.

Thanks!

**Comment by farizrahman4u** [comment]
I am waiting for keras 1.0. Any work that we do now might be worthless in a few days.
