### ISSUE TITLE
'Seq2seq' object has no attribute 'layers'

### ISSUE THREAD

**Issue by nicolas-ivanov** [farizrahman4u/seq2seq#6]
Launching the vanila code from the documentation example leads to the following error:
```
/usr/bin/python2.7 /home/nicolas/Code/seq2seq/try.py
Traceback (most recent call last):
  File "/home/nicolas/Code/seq2seq/try.py", line 13, in <module>
    output_dim=embedding_dim, output_length=maxlen, batch_size=10, depth=4)
  File "/home/nicolas/Code/seq2seq/seq2seq.py", line 59, in __init__
    self.add(l)
  File "/usr/local/lib/python2.7/dist-packages/keras/layers/containers.py", line 35, in add
    self.layers.append(layer)
AttributeError: 'Seq2seq' object has no attribute 'layers'
```
What's wrong?

For the reference the code is
```python
import keras
from keras.models import Sequential
from keras.layers.embeddings import Embedding
from seq2seq import Seq2seq
from keras.preprocessing import sequence

vocab_size = 20000 #number of words
maxlen = 100 #length of input sequence and output sequence
embedding_dim = 200 #word embedding size
hidden_dim = 500 #memory size of seq2seq

embedding = Embedding(vocab_size, embedding_dim, input_length=maxlen)
seq2seq = Seq2seq(input_length=maxlen, input_dim=embedding_dim,hidden_dim=hidden_dim,
                  output_dim=embedding_dim, output_length=maxlen, batch_size=10, depth=4)

model = Sequential()
model.add(embedding)
model.add(seq2seq)
```

**Comment by farizrahman4u** [comment]
@nicolas-ivanov : This has been fixed.
