### ISSUE TITLE
Exception: AttentionDecoder requires input_length.

### ISSUE THREAD

**Issue by chimkiu** [farizrahman4u/seq2seq#70]
Hi!

Running this simple script with AttentionSeq2seq gives exceptions due to the absence of the parameter **input_length** although he indicated when creating a model.

seq2seq.py:
```#!/usr/bin/python

import seq2seq
from seq2seq.models import AttentionSeq2seq

def main():
  model = AttentionSeq2seq(input_dim=5, input_length=10, hidden_dim=256, output_length=8, output_dim=15, depth=3)
  model.compile(loss='mse', optimizer='rmsprop')

if __name__ == "__main__":
  main()
```

run it:

```
$ python seq2seq.py
Using Theano backend.
WARNING (theano.tensor.blas): Failed to import scipy.linalg.blas, and Theano flag blas.ldflags is empty. Falling back on slower implementations for dot(matrix, vector), dot(vector, matrix) and dot(vector, vector) (No module named scipy.linalg.blas)
Traceback (most recent call last):
  File "seq2seq.py", line 12, in <module>
    main()
  File "seq2seq.py", line 8, in main
    model = AttentionSeq2seq(input_dim=5, input_length=10, hidden_dim=256, output_length=8, output_dim=15, depth=3)
  File "/home/chimkiu/Dropbox/script/translate/keras/seq2seq/models.py", line 220, in __init__
    self.add(decoder)
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 146, in add
    output_tensor = layer(self.outputs[0])
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 458, in __call__
    self.build(input_shapes[0])
  File "/home/chimkiu/Dropbox/script/translate/keras/seq2seq/layers/decoders.py", line 237, in build
    raise Exception ('AttentionDecoder requires input_length.')
Exception: AttentionDecoder requires input_length.
```

**Comment by farizrahman4u** [comment]
Fixed.
