### ISSUE TITLE
Seq2seq example model not working

### ISSUE THREAD

**Issue by chm90** [farizrahman4u/seq2seq#71]
Hi. First of all thanks for the good work with this library!
My problem is that i'm not able to create any Seq2seq model, not even the example model.

Running

```python
import seq2seq
from seq2seq.models import Seq2seq
model = Seq2seq(batch_input_shape=(16, 7, 5), hidden_dim=10, output_length=8, output_dim=20, depth=4, peek=True)
model.compile(loss='mse', optimizer='rmsprop')
```
using the tensorflow backend yields 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/seq2seq/models.py", line 143, in __init__
    self.add(decoder)
  File "/usr/local/lib/python3.5/dist-packages/keras/models.py", line 146, in add
    output_tensor = layer(self.outputs[0])
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 485, in __call__
    self.add_inbound_node(inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 543, in add_inbound_node
    Node.create_node(self, inbound_layers, node_indices, tensor_indices)
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/topology.py", line 148, in create_node
    output_tensors = to_list(outbound_layer.call(input_tensors[0], mask=input_masks[0]))
  File "/usr/local/lib/python3.5/dist-packages/seq2seq/layers/decoders.py", line 116, in call
    y_0 = K.permute_dimensions(X, (1, 0, 2))[0]
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_ops.py", line 167, in _SliceHelper
    sliced = slice(tensor, indices, sizes)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_ops.py", line 217, in slice
    return gen_array_ops._slice(input_, begin, size, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 1318, in _slice
    name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/op_def_library.py", line 655, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 2156, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1612, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/array_ops.py", line 865, in _SliceShape
    input_shape.assert_has_rank(ndims)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/tensor_shape.py", line 605, in assert_has_rank
    raise ValueError("Shape %s must have rank %d" % (self, rank))
ValueError: Shape (8, 16, 10) must have rank 1

```

I use python 3.5, Keras 1.05, tensorflow 0.8.0 and just pulled the lates version of seq2seq.
Does this work for someone else or might Seq2seq be broken?

**Comment by farizrahman4u** [comment]
I have made an update. Can you try again?

**Comment by chm90** [comment]
Just did, unfortunately still the same result.

**Comment by meain** [comment]
@chm90 Hey, I could not reproduce the issue. It was working perfectly fine for me. Try reinstalling seq2seq maybe?
