### ISSUE TITLE
Cannot create Model

### ISSUE THREAD

**Issue by ftrier** [farizrahman4u/seq2seq#86]
> Traceback (most recent call last):
  File "train.py", line 382, in <module>
    train_model(nn_model, w2v_model, tokenized_lines, index_to_token)
  File "train.py", line 355, in train_model
    save_model(nn_model)
  File "train.py", line 329, in save_model
    nn_model.save_weights(NN_MODEL_PATH, overwrite=True)
  File "/home/t/anaconda2/lib/python2.7/site-packages/keras/engine/topology.py", line 2315, in save_weights
    f = h5py.File(filepath, 'w')
  File "/home/t/anaconda2/lib/python2.7/site-packages/h5py/_hl/files.py", line 260, in __init__
    fid = make_fid(name, mode, userblock_size, fapl, swmr=swmr)
  File "/home/t/anaconda2/lib/python2.7/site-packages/h5py/_hl/files.py", line 95, in make_fid
    fid = h5f.create(name, h5f.ACC_TRUNC, fapl=fapl, fcpl=fcpl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2579)
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper (/home/ilan/minonda/conda-bld/work/h5py/_objects.c:2538)
  File "h5py/h5f.pyx", line 96, in h5py.h5f.create (/home/ilan/minonda/conda-bld/work/h5py/h5f.c:1989)
IOError: Unable to create file (Unable to open file: name = 'models/_w300_l6_s16_b32_m1_d2', errno = 70, error message = 'communication error on send', flags = 13, o_flags = 242)

Interestingly this only happens after many iterations at some point. Sorry I am completely vague, currently I do not have more information. My code is based on https://github.com/nicolas-ivanov/debug_seq2seq/blob/24888cefd5e3d104f002e0b17b4ce990f054c7f2/lib/nn_model/train.py. Besides using other data, it is mostly the same - I did not change anything in the save procedure.

**Comment by ftrier** [comment]
I have changed the method, now the file is less often opened and closed/saved. Now it does not crash anymore. Also this has only happened on a specific computer configuration. So I am assuming this has nothing to do with Seq2Seq/Keras/Theano. So I will close this issue.
