### ISSUE TITLE
Seq2Seq Batch Input Shape problem

### ISSUE THREAD

**Issue by techscientist** [farizrahman4u/seq2seq#97]
Hi,

I was trying this library, but for some reason, the batch_input_shape parameter isn't working (as shown in the example)

Here is the exception:
```
Traceback (most recent call last):
  File "playlist_gen_v2.py", line 121, in <module>
    smodel.fit(X, Y, nb_epoch=epochs, batch_size=32, verbose=1, callbacks=[early_stopping, checkpoint])
  File "/usr/local/lib/python2.7/dist-packages/keras/models.py", line 620, in fit
    sample_weight=sample_weight)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 1032, in fit
    batch_size=batch_size)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 963, in _standardize_user_data
    exception_prefix='model target')
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 97, in standardize_input_data
    str(array.shape))
Exception: Error when checking model target: expected timedistributed_1 to have 3 dimensions, but got array with shape (9080, 51)
```

In my case, the batch_input_shape is in the form: (num_samples, timesteps, features). My code is almost exactly the same as the advanced seq2seq with batch_input_shape example.

Can you kindly help me on this? @farizrahman4u

**Comment by sallamander** [comment]
@techscientist Do you have a link to the code you're using?

**Comment by hqsiswiliam** [comment]
@techscientist you may need to reshape your label as well.
